---
title: "About Me"
about:
  id: me
  template: broadside
---

:::{#me}

## Goals

Collaborate on solving environmental issues using current statistical and analytical tools using the R language environment for statistical computing within the RStudio IDE.

## Education

Ph.D. in Wastewater engineering with thesis on the use of anaerobic membrane bioreactors for the treatment of municipal sludge [Thesis](). M.A.Sc in advanced wastewater treatment and applied management. B.A.Sc. in Civil Engineering. A professional engineer (P.Eng.) in the province of Ontario [PEO](https://www.peo.on.ca/). Currently pursuing accreditation as an Associate Statistician (A.Stat.) through the Canadian Statistical Society [CSS](https://ssc.ca/en).

## Experience

Research in wastewater treatment (and sludge) for trace contaminants, microplastics and legacy pollutants. Worked on wastewater epidemiology investigating COVID in wastewater during the COVID pandemic. Developed design guidelines for wastewater treatment including extensive statistical analysis and assessment with reporting and publications. Actively engaged in supporting the regulatory role and oversight in Ontario related to municipal centralized and decentralized wastewater and sludge treatment.

*   Research Gate (RI Score: 339; Citations: 493; H-index: 10; Read: > 10,750; Recommendations: 53) [RG](https://www.researchgate.net/profile/Vince-Pileggi)
*   LinkedIn [Lnk](https://www.linkedin.com/feed/)


:::

***Currently Under Development.***. **Thanks for checking out my web site!**
